Add more helpful content
qualiticcommunity/qualiticcommunity.github.io pull request #47
Opened 2022-01-26 16:53 UTC by emranbm

I've added more new content on the latter page, in comparison to the previously-reviewed google-doc. Furthermore, the home page itself has changed a little bit.  
Please kindly review the new content for the homepage and the maturity model page.

2022-01-26 16:56 UTC, emranbm commented
The failure of the Jekyll build job is gonna be fixed in #46.

2022-01-29 10:11 UTC, mojyou commented on MATURITY_MODEL.md
> +Although, many non-trivial issues also can be checked automatically (with a more complexity, off course), it's recommended to keep this stage fast enough to deliver early feedback to the developer, m
of course?

2022-01-29 10:46 UTC, mojyou reviewed
Thanks

2022-01-29 12:19 UTC, emranbm commented on MATURITY_MODEL.md
> +Although, many non-trivial issues also can be checked automatically (with a more complexity, off course), it's recommended to keep this stage fast enough to deliver early feedback to the developer, m
removed the extra 'f'. Thanks.

2022-01-29 12:29 UTC, mojyou approved these changes
Thanks dude.

2022-01-30 12:53 UTC, littleali requested changes

2022-01-30 12:53 UTC, littleali commented on MATURITY_MODEL.md
> +It's also assumed that the pipeline has at least five (abstract) steps, as mentioned in the next sections. In each item, there is a field named `Applied Stage` that helps where that item best fits to
to be cared -> to care.

2022-01-30 12:53 UTC, littleali commented on MATURITY_MODEL.md
> +Generally, commit stage ensures that a change is worth reviewing by a human-being; since many trivial issues (like compile error) can be caught by machine, instead of a developer.
Generally, "the" commit.

caught by "a" machine.

2022-01-30 12:53 UTC, littleali commented on MATURITY_MODEL.md
> +Although, many non-trivial issues also can be checked automatically (with a more complexity, of course), it's recommended to keep this stage fast enough to deliver early feedback to the developer, mo
Although(remove comma)

2022-01-30 12:53 UTC, littleali commented on MATURITY_MODEL.md
> +Although, many non-trivial issues also can be checked automatically (with a more complexity, of course), it's recommended to keep this stage fast enough to deliver early feedback to the developer, mo
With a more-> remove "a"

2022-01-30 12:53 UTC, littleali commented on MATURITY_MODEL.md
> +As mentioned above, not all issues of a suggested change are detected by the commit stage and hence it needs a manual review - usually by a co-worker.
stage and -> stage, and

2022-01-30 12:53 UTC, littleali commented on MATURITY_MODEL.md
> +The final stage, before releasing the change into production, is named _Staging_. Here the (recently-changed) product is deployed to a production-like environment (with the exact architecture, infras
Further more -> Furthermore

2022-01-30 12:53 UTC, littleali commented on MATURITY_MODEL.md
> +This category is about how the product is delivered to the end users. Currently, there are four metrics for it that are described below.
end users -> end-users

2022-01-30 12:53 UTC, littleali commented on README.md
> +Although it's ideal for a product to be developed at highest level of quality, there's no general advice for all products to progress at a specific level; as there are some other factors that affect
at highest -> at the highest

2022-01-30 12:53 UTC, littleali commented on README.md
> +Qualitic Maturity Model is described in details [here](/MATURITY_MODEL.html).
described in details -> detail (remove s)

2022-01-30 13:30 UTC, littleali approved these changes

2022-01-30 13:30 UTC, merged